# Generated by Django 6.0.3 on 2026-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zambiandistrict',
            name='population',
            field=models.PositiveIntegerField(default=0, help_text='Estimated resident population, used to compute cases-per-10,000 incidence rate. Leave as 0 if unknown — hotspot tiers fall back to raw case counts.'),
        ),
    ]
