# Generated by Django 6.0.3 on 2026-08-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0002_zambiandistrict_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratedmalariadata',
            name='suspected_cases',
        ),
    ]
