# Generated by Django 6.0.3 on 2026-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0004_systemuser_totp_enabled_systemuser_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedmalariadata',
            name='microscopy_tested',
            field=models.IntegerField(default=0, help_text='Number tested by microscopy, if reported.'),
        ),
        migrations.AddField(
            model_name='integratedmalariadata',
            name='rdt_tested',
            field=models.IntegerField(default=0, help_text='Number tested by RDT, if reported — enables a real positivity rate (rdt_confirmations / rdt_tested).'),
        ),
        migrations.AddField(
            model_name='integratedmalariadata',
            name='suspected_cases',
            field=models.IntegerField(default=0, help_text='Suspected cases before testing, if reported.'),
        ),
    ]
